# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0007_member_memberkeyid'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.Item')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.Seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
