# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_memberkeyid'),
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='buyers',
            field=models.ManyToManyField(to='members.Buyer'),
        ),
    ]
