# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_auto_20170530_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerce',
            old_name='Item',
            new_name='item',
        ),
    ]
