# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('solution', '0004_auto_20170530_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceSellRegression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bias', models.FloatField(blank=True, default=None, null=True)),
                ('cost', models.FloatField(blank=True, default=None, null=True)),
                ('distance_w', models.FloatField(blank=True, default=None, null=True)),
                ('distance_pValue', models.FloatField(blank=True, default=None, null=True)),
                ('timer_w', models.FloatField(blank=True, default=None, null=True)),
                ('timer_pValue', models.FloatField(blank=True, default=None, null=True)),
                ('price_w', models.FloatField(blank=True, default=None, null=True)),
                ('price_pValue', models.FloatField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PopularText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contentTextWithDelimiter', models.CharField(default='', max_length=200)),
                ('titleTextWithDelimiter', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
