# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0005_commercesellregression_populartext'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercesellregression',
            name='adjr2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
