# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0006_commercesellregression_adjr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='buyCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commerce',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commerce',
            name='sendCount',
            field=models.IntegerField(default=0),
        ),
    ]
