# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0007_auto_20170601_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercesellregression',
            name='distance_Sdeviation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commercesellregression',
            name='distance_average',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commercesellregression',
            name='price_Sdeviation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commercesellregression',
            name='price_average',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commercesellregression',
            name='timer_Sdeviation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commercesellregression',
            name='timer_average',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
