# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('memberName', models.CharField(default='', max_length=200)),
                ('userId', models.CharField(default='', max_length=200, unique=True)),
                ('memberDivision', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.MemberDivision')),
            ],
            options={
                'ordering': ['memberName'],
            },
        ),
    ]
