# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('members', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.Member')),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('fcm', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', '남자'), ('W', '여자')], default='남자', max_length=200)),
                ('isLocationAgree', models.BooleanField(default=False)),
                ('isPushAgree', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(blank=True, max_length=200)),
                ('items', models.ManyToManyField(to='commerce.Item')),
            ],
            options={
                'ordering': ['member'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.Member')),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('fcm', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', '남자'), ('W', '여자')], default='남자', max_length=200)),
                ('isLocationAgree', models.BooleanField(default=False)),
                ('isPushAgree', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
