# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memberDivision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.MemberDivision'),
        ),
    ]
