# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_memberdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memberKeyId',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
