# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_memberkeyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
